config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'posts#index'
  resources :posts do
    member do
      put "like", to: "posts#like"
      put "unlike", to: "posts#unlike"
    end
    resources :comments
  end
  resources :users, only: [:show, :edit, :update]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
 belongs_to :user
 has_many :comment, dependent: :destroy
 has_many :likes

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 
 validates :email, presence: true
 mount_uploader :avatar, AvatarUploader
 has_many :posts
 has_many :comment, dependent: :destroy
 has_many :likes

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
  before_action :comment_owner, only: [:destroy, :edit, :update]
  
  def create
    @comment = @post.comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.save
    
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  def edit
  
  end
  
  def update
    if @comment.update(params[:comment].permit(:content))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end
  
  private
  
  def find_post
 @post = Post.find(params[:post_id])
  end
  
  def find_comment
    @comment = @post.comment.find(params[:id])
    
  end
  
  def comment_owner
    unless current_user.id == @comment.user_id
    flash[:notice] = "İzinsiz erişim!"
    redirect_to @post
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy,:like, :unlike]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end
  

  # GET /posts/1
  # GET /posts/1.json
  def show
    @likeds=Like.where(post: @post).all
    @comments = Comment.where(post_id: @post).order("created_at ASC")
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Başarıyla Oluşturuldu.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Güncelleme başarılı.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Silindi.' }
      format.json { head :no_content }
    end
  end
  
  def like    
    @l=Like.new    
      @l.post=@post    
      @l.user=current_user    
      @l.save    
      respond_to do |format|      
       format.js {render layout: false}      
       format.json    
    end  
  end
  
  def unlike    
      @l=Like.where(post:@post,user:current_user).first    
      @l.destroy    
      respond_to do |format|      
        format.js {render layout: false}      
        format.json    
      end  
  end 


  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :msg, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:edit,:update]
    before_action :check_authorization, only: [:edit, :update]
    before_action :set_user 
    def show
        @user = User.find(params[:id])
    end
    
    def edit
        
    end
    
    def update
      if @user.update(user_params)
        redirect_to @user
      else
        flash.now[:alert] = "Hata oluştu. Tekrar deneyin."
        render :edit
      end
    end
    
    private
    
    def check_authorization
      unless current_user.id == params[:id].to_i
        redirect_to root_url
      end
    end
    
    def set_user
        @user = User.find(params[:id])
    end
        
    def user_params
      params.require(:user).permit(:email, :avatar, :descriptions)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def avatar_for(user, options = {size: 80 })
        size= options[:size]
        if user.avatar?
            image_tag user.avatar.url(:thumb), width: size, class: 'avatar-image'
        else
            image_tag "default-avatar.png", width: size, class: 'avatar-image'
        end
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/comments/_comment.html.erb
<h4><%= @comments.count %> yorum</h4>

<% @comments.each do |comment| %>
    <p><b><%= comment.user.email %> </b></p>
    <p><%= comment.content %></p>
    
    <% if current_user == comment.user %>
        <%= link_to '', [comment.post, comment], method: :delete, data: { confirm: 'Silinsin mi?' }  ,class:"glyphicon glyphicon-trash"%>
        |
        <%= link_to '', edit_post_comment_path(comment.post, comment), class:"glyphicon glyphicon-pencil" %><br><br
    <% end %>
<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comment.build]) do |f| %>

    <%= f.text_area :content%><br>
    <%= f.submit %>

<% end %>

app/views/comments/edit.html.erb
 <%= form_for([@post, @comment]) do |f| %>

    <%= f.text_area :content %>
    <%= f.submit %>

<% end %>

app/views/layouts/_footer.html.erb
        </div>
    <div class="row">
    	<div class="col-md-12"></div>
        <footer class="container-fluid text-center">
<p>&copy; 2017 DİLAN YARDIMCI</p>
</footer>
    </div>	
</div>

app/views/layouts/application.html.erb
<html>
<head>
<head>
  <title>DİLAN YARDIMCI</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta charset="utf-8">
<meta content="IE=edge" http-equiv="X-UA-Compatible">
<meta content="width=device-width, initial-scale=1" name="viewport">
<link rel="stylesheet" media="all" href="/assets/application-43731e821df91524293c7ce3792cd9367b6509f24378b041d84c093e17f67a23.css" data-turbolinks-track="true">
<script src="/assets/application-a3d1d0a5e44dcc62e891e1705804bfcbcbe077456c5ac43eb511691e1ef69a77.js" data-turbolinks-track="true"></script><style></style>
<meta name="csrf-param" content="authenticity_token">
<meta name="csrf-token" content="DCybKZLEYbiR15eGHVZ2lmR5AzYKigMoaAlF9ugjTx/A7idrkiKUpGZDV0bDz4/LJnD1zQgbLYrCNESIlzCMlQ==">

<body>
<nav class="navbar navbar-default">
		<div class="container">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">DİLAN YARDIMCI</a>
    </div>

      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %> 
                  <li><%= link_to avatar_for(current_user, size: 15), current_user %> </li>
                <li> <%= link_to 'Çıkış Yapınız', destroy_user_session_path %></li>
                <% else %>
                   <li><%= link_to 'Kayıt Olunuz', new_user_registration_path %></li>
                   <li><%= link_to 'Giriş Yapınız', new_user_session_path %></li>
                <% end %>
    </ul>

  </div>
    </div>
</nav>    

<div class="row">
 
        

    	<div class="col-md-2">
     	<ul class="nav navbar-nav">
      <li><%= link_to "Paylaşım", posts_url, class:"glyphicon glyphicon-th" %></li><br>
      <li><%= link_to 'Yeni', new_post_path, class:"glyphicon glyphicon-plus" %></li><br>
      <li><%= link_to "Profil", current_user, class:"glyphicon glyphicon-user" %></li><br>
    </ul>
        </div>
        
         <div class="col-md-10">
        
         <%=yield%>
        </div>
     
     </div>   
<%= render 'layouts/footer' %>	
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div><br>
  <div class="field">
    <%= f.label :msg %><br>
    <%= f.text_area :msg %>
  </div><br>
  <div class="field">
  <%= f.label :image %>
  <%=f.file_field :image %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Göster', @post %> |
<%= link_to 'Geri', posts_path %>

app/views/posts/index.html.erb
<div class="col-md-12">
        <div class="row">
          <% @posts.each do |post| %>

            <div class="panel panel-default widget">

                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-2 col-md-1">
                                    <%= link_to image_tag post.user.avatar.url(:thumb) if post.user.avatar?%>
                                </div>
                                <div class="col-xs-10 col-md-11">
                                    <div>
                                        <div class="mic-info">
                                             <a href="users/<%=post.user.id%>"> <%=post.user.email%> </a> <%=post.created_at.strftime("%b.%d.%Y, %H:%M")%> 
                                        </div>
                                    </div>
                                    <div class="comment-text">
                                        <%=post.title%> <br/>
                                        <%=image_tag post.image.url(:medium),class:"img img-responsive" if post.image?%>
                                        <br/>
                                        <%=post.msg%>
                                    </div>
                                    
                                    <div class="action">
                                      <div id="<%=post.id%>">
                                      <%if Like.where(user:current_user, post:post).count>0%>
                                         <%= link_to "", unlike_post_path(post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>
                                      <%else%>
                                         <%= link_to "", like_post_path(post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>
                                      <%end%>
                                      </div><br>
                                     <%= link_to '', post_path(post),class:"glyphicon glyphicon-hand-right" %>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <%end%>
        </div>
    </div>

app/views/posts/like.js.erb
$('#<%=@post.id%>').html('<%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>')

app/views/posts/new.html.erb
<h4>Yeni Paylaşım</h4>
<div class="panel panel-default widget">
  <div class="panel-body">
    <%= render 'form', post: @post %>
  </div>
</div>

<%= link_to 'Geri', posts_path %>

app/views/posts/show.html.erb
<div class="panel panel-default widget">

    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item">
                <div class="row">
                    <div class="col-xs-2 col-md-1">
                        <%=image_tag @post.user.avatar.url(:thumb) if @post.user.avatar?%>
                    </div>
                    <div class="col-xs-10 col-md-11">
                        <div>
                            <div class="mic-info">
                                 <a href="?user=<%=@post.user.id%>"> <%=@post.user.email%> </a> <%=@post.created_at.strftime("%b.%d.%Y, %H:%M")%>
                            </div>
                        </div>
                        <div class="comment-text">
                            <%=@post.title%> <br/>
                            <%=image_tag @post.image.url,class:"img img-responsive" if @post.image?%>
                            <br/>
                            <%=@post.msg%>
                        </div>
                        <div id="<%=@post.id%>">
                          <%if Like.where(user:current_user, post:@post).count>0%>
                             <%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>
                          <%else%>
                             <%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>
                          <%end%>
                          </div>
                        <hr>
                        Bunu beğenenler(<%=@likeds.count%>) <br/>
                        <% @likeds.each do |l|%>
                          <%=image_tag l.user.avatar.url(:thumb)%>
                          <%=l.user.email%>
                        <% end %>
                        </hr>
                        <hr>
                        <%=render 'comments/comment'%>
                        </hr>
                        <hr>
                        <% if @post.user.id == current_user.id %>
                        <%= link_to 'Düzenle', edit_post_path %> 
                        |
                        <%= link_to 'Sil',  { action: :destroy, id: @post.id }, method: :delete, data: { confirm: 'Silinsin mi?' } %>
                        
                        <% end %>
                        
                        </hr>
                    </div>
            </li>
        </ul>
    </div>
</div>

app/views/posts/unlike.js.erb
$('#<%=@post.id%>').html('<%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>')

app/views/users/edit.html.erb
<h1>Profilimi Düzenle</h1>
<%= form_for(@user, html: {multipart: true}) do |f| %>

 <%= f.label :Email %><br>
 <%= f.text_field :email %><br><br>
  
 <%= f.label :Hakkımda %><br>
 <%= f.text_area :descriptions %><br><br>
 
 <%= f.label :Fotoğraf %> 
 <%= f.file_field :avatar %><br>
 
 <%= f.submit "Güncelle." %>
<% end %>

app/views/users/show.html.erb
<h4><%= @user.email %></h4><br>
<%= avatar_for(@user) %>
<%= @user.descriptions %>
<%= link_to "Düzenle", edit_user_path(@user) %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>